### ISSUE TITLE
Is possible to provide some error codes with validation errors?

### ISSUE THREAD

**Issue by kirillsalykin** [funcool/struct#2]
§Similar to github API https://developer.github.com/v3/#client-errors

Change validation result to something like this:

```
[{:year ("must be a number")} {:name "Blood of Elves", :year "1994"}]
```

```
[{:year ("not_number", "must be a number")} {:name "Blood of Elves", :year "1994"}]
```

**Comment by niwinz** [comment]
Hmm, yes it is possible I think. Just attach a proper `:message` property to the validator:

`(assoc st/number :message '("not_number", "must be a number"))`

At this moment `{:year ("must be a number")}` the errors are wrapped in a list because on the first moment, more than one error can be posible per field. But with the current implementation, only one error is possible per field, so the list wrapping is useless.

I have explained that for you because, with the current implementation, your solution will result in something like this: `{:year (("not_number", "must be a number"))}` because as I can understand, you want express one error as list of message and code... and the current impl returns a list of errors...

But, I have plans for the next release remove useless list wraping because the implementation is done in the way that only one error is possible for field, so in the next release the list wraping will deisapear.

**Comment by kirillsalykin** [comment]
Clear, thanks!
